name: PR

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  meticulous-test:
    name: Meticulous test
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Makes turbo cache checking faster, since can use commit history rather than having to hash files
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/cache-build
      - run: |
          yarn workspace @calcom/web start &
          sleep 5
      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:3000"
