name: PR Update

on:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  meticulous-test:
    name: Meticulous test
    uses: ./.github/workflows/meituclous-test.yml
    secrets: inherit

  required:
    needs: [lint, type-check, meticulous-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
